---
title: "Аудіовізуальна електронна листівка"
hero_image: images/banner.png
description: Створи аудіовізувальну електронну листівку за допомогою Скретч
version: 4
listed: true
copyedit: true
last_tested: "2020-08-21"
steps:
  - 
    title: Вступ
  - 
    title: Запиши власне відео
  - 
    title: Додай свій GIF
  - 
    title: Додай трохи звуку
  - 
    title: Поділися своєю електронною листівкою з друзями та родиною
