---
title: "Een audiovisuele e-card"
hero_image: images/banner.png
description: Maak een audiovisuele e-card met Scratch
version: 4
listed: true
copyedit: true
last_tested: "2020-08-21"
steps:
  - 
    title: Inleiding
  - 
    title: Neem je video op
  - 
    title: Voeg je GIF toe
  - 
    title: Voeg wat geluid toe
  - 
    title: Deel je e-card met vrienden en familie
