title: "An audiovisual e-card"
hero_image: images/banner.png
description: av-e-card description
version: 4
listed: false
copyedit: false
last_tested: "2020-04-15"
steps:
  - title: Introduction
  - title: Record your video
  - title: Add your GIF
  - title: Add some sound
  - title: Share your e-card with friends and family
