title: "An Audio/Visual e-card"
hero_image: images/banner.png
description: av-e-card description
version: 4
listed: false
copyedit: false
last_tested: "2020-04-15"
steps:
  - title: Introduction
  - title: Recording your video
  - title: Adding your GIF
  - title: Adding some sound
  - title: Sharing with friends and family
