---
title: "एक अनोखा ई-कार्ड"
hero_image: images/banner.png
description: Scratch के माध्यम से एक अनोखा ई-कार्ड बनाएं
version: 4
listed: false
copyedit: false
last_tested: "2020-04-15"
steps:
  - title: परिचय
  - title: अपना वीडियो रिकॉर्ड (video record) करें
  - title: अपना GIF जोड़ें
  - title: कुछ आवाज़ जोड़ें
  - title: अपने ई-कार्ड को दोस्तों और परिवार के साथ शेयर (share) करें
