---
title: An audiovisual e-card
hero_image: images/banner.png
description: Create an audiovisual e-card with Scratch
version: 4
listed: true
copyedit: true
last_tested: '2020-08-21'
steps:
  - 
    title: Introduction
  - 
    title: Record your video
  - 
    title: Add your GIF
    completion:
      - engaged
  - 
    title: Add some sound
    completion:
      - internal
  - 
    title: Share your e-card with friends and family
