---
title: "Um cartão eletrônico audiovisual"
hero_image: images/banner.png
description: Crie um cartão eletrônico audiovisual com o Scratch
version: 4
listed: true
copyedit: true
last_tested: "2020-08-21"
steps:
  - 
    title: Introdução
  - 
    title: Grave seu vídeo
  - 
    title: Adicione seu GIF
  - 
    title: Adicione um som
  - 
    title: Compartilhe seu cartão eletrônico com amigos e familiares
