---
title: Una targeta audiovisual electrònica
hero_image: images/banner.png
description: Crea una targeta audiovisual electrònica amb Scratch
version: 4
listed: true
copyedit: true
last_tested: '2020-08-21'
steps:
  - 
    title: Introducció
  - 
    title: Grava el teu vídeo
  - 
    title: Afegeix el teu GIF
    completion:
      - engaged
  - 
    title: Afegeix algun so
    completion:
      - internal
  - 
    title: Comparteix la teva targeta electrònica amb amics i familiars
