---
title: "Una tarjeta electrónica audiovisual"
hero_image: images/banner.png
description: Crea una tarjeta electrónica audiovisual con Scratch
version: 4
listed: false
copyedit: false
last_tested: "2020-04-15"
steps:
  - title: Introducción
  - title: Graba tu video
  - title: Añade tu GIF
  - title: Añade algo de sonido
  - title: Comparte tu tarjeta electrónica con amigos y familiares
