---
title: "بطاقة إلكترونية سمعية بصرية"
hero_image: images/banner.png
description: قم بأنشاء بطاقة إلكترونية سمعية بصرية بإستخدام برنامج Scratch
version: 4
listed: false
copyedit: false
last_tested: "2020-04-15"
steps:
  - title: المقدمة
  - title: قم تسجيل الفيديو الخاص بك
  - title: أضف ملف GIF
  - title: أضف الصوت
  - title: شارك بطاقتك الإلكترونية مع الأصدقاء والعائلة
