---
title: "시청각 전자 카드"
hero_image: images/banner.png
description: 스크래치로 시청각 전자 카드 만들기
version: 4
listed: false
copyedit: false
last_tested: "2020-04-15"
steps:
  - 
    title: 소개
  - 
    title: 동영상 녹화하기
  - 
    title: GIF 추가하기
  - 
    title: 소리 추가하기
  - 
    title: 시청각 전자 카드를 친구, 가족과 공유하기
