---
title: "Audiowizualna e-pocztówka"
hero_image: images/banner.png
description: Utwórz audiowizualną e-pocztówkę za pomocą Scratch
version: 4
listed: false
copyedit: false
last_tested: "2020-04-15"
steps:
  - 
    title: Wprowadzenie
  - 
    title: Nagraj swoje wideo
  - 
    title: Dodaj swój GIF
  - 
    title: Dodaj trochę dźwięku
  - 
    title: Podziel się swoją e-pocztówką z rodziną i znajomymi
