---
title: Μια οπτικοακουστική ηλεκτρονική κάρτα
hero_image: images/banner.png
description: Δημιούργησε μια οπτικοακουστική ηλεκτρονική κάρτα με το Scratch
version: 4
listed: false
copyedit: false
last_tested: '2020-04-15'
steps:
- title: Εισαγωγή
  completion: engaged
- title: Κατέγραψε το βίντεό σου
- title: Πρόσθεσε το GIF σου
- title: Πρόσθεσε λίγο ήχο
  completion: internal
- title: Διαμοιράσου την ηλεκτρονική σου κάρτα με φίλους και συγγενείς
