---
title: "Une carte virtuelle multimédia"
hero_image: images/banner.png
description: Crée une carte virtuelle multimédia avec Scratch
version: 4
listed: true
copyedit: true
last_tested: "2020-08-21"
steps:
  - 
    title: Introduction
  - 
    title: Enregistre ta vidéo
  - 
    title: Ajoute ton GIF
  - 
    title: Ajoute du son
  - 
    title: Partage ta carte virtuelle avec tes amis et ta famille
